version: "3.8"

services:
  mysql_shop_springboot:
    container_name: mysql_shop_springboot
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - ./shop-springboot.sql:/docker-entrypoint-initdb.d/shop-springboot.sql
      - ./db_data:/var/lib/mysql

volumes:
  db_data: {}